/* AUTO-GENERATED from 'QUOTE ESTIMATOR - FA.csv' (2026-07-20). Every spec line below is
   VERBATIM from that sheet — only the bracketed placeholders ([HEIGHT] [WIDTH] [DEPTH]
   [APPLICATION] [ASK REP]) are substituted at render time. Do not hand-edit generated
   lines; regenerate from the sheet instead (docs/sign-matrix/). */

export const FA_FAMILY_ORDER = ["ILLUMINATED CHANNEL LETTERS", "NON ILLUMINATED FABRICATED CHANNEL LETTERS", "DIMENSIONAL FLAT CUT LETTERS", "ILLUMINATED CABINETS", "NON ILLUMINATED CABINETS", "BLADE SIGNS", "LED NEON SIGNS"]

// Each group = one Sign Type card in the wizard. `leaves` = every concrete
// (thickness ×) mounting combination the sheet defines for it.
export const FA_SIGN_GROUPS = [
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "HALO LIT CHANNEL LETTERS",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : HALO LIT CHANNEL LETTERS"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "\"SIGN TYPE : HALO LIT CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\"\" X [WIDTH]\"\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\"\""}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\"\" DEEP 6\"\" TALL ALUMINUM RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]\""}, {"t": "text", "v": ""}, {"t": "text", "v": "•⁠  ⁠POWER SUPPLY TO BE INSIDE RACEWAY, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : HALO LIT CHANNEL LETTER WITH BACKBOARD"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 2\" DEEP ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "•⁠  ⁠POWER SUPPLY TO BE INSIDE BACKER, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : HALO LIT CHANNEL LETTER WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER : 2.5MM FLAT ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : HALO LIT CHANNEL LETTER WITH ACM BACKER"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER : 4MM FLAT ACM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : HALO LIT CHANNEL LETTER WITH ACRYLIC BACKER"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER : 8MM FLAT ACRYLIC BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "FACE LIT CHANNEL LETTERS",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE LIT CHANNEL LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE LIT CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "LETTER FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "LETTER RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP, 6\" TALL ALUMINUM RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "•⁠  ⁠POWER SUPPLY TO BE INSIDE RACEWAY, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE LIT CHANNEL LETTERS WITH BACKBOARD"}, {"t": "text", "v": "LETTER FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "LETTER RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 2\" DEEP ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "•⁠  ⁠POWER SUPPLY TO BE INSIDE BACKER, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE LIT CHANNEL LETTERS WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 2.5MM FLAT ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE LIT CHANNEL LETTERS WITH ACM BACKER"}, {"t": "text", "v": "FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 4MM ACM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE LIT CHANNEL LETTERS WITH ACRYLIC BACKER"}, {"t": "text", "v": "FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATION : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 8MM ACRYLIC BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "FACE AND HALO LIT CHANNEL LETTERS",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE AND HALO LIT CHANNEL LETTERS"}, {"t": "text", "v": "LETTER FACE: ACRYLIC/POLYCARBONATE FACE WITH VINYL APPLICATION"}, {"t": "text", "v": "BACK: ACRYLIC BACK"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "TRIM & RETURN COLOR", "v": "  • TRIM & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "LETTER FACE: WHITE ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP, 6\" TALL ALUMINUM RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "•⁠  ⁠POWER SUPPLY TO BE INSIDE RACEWAY, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS WITH ALUMINUM BACKBOARD"}, {"t": "text", "v": "LETTER FACE: WHITE ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 2\" DEEP ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "•⁠  ⁠POWER SUPPLY TO BE INSIDE BACKER, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS WITH ALUMINUM BACKER"}, {"t": "text", "v": "LETTER FACE: WHITE ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 2MM FLAT ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS WITH ACM BACKER"}, {"t": "text", "v": "LETTER FACE: WHITE ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 4MM ACM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS WITH ACRYLIC BACKER"}, {"t": "text", "v": "LETTER FACE: WHITE ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: METALLIC/STANDARD TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "BACKER: 8MM ACRYLIC BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "MARQUEE CHANNEL LETTERS",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: MARQUEE CHANNEL LETTERS"}, {"t": "text", "v": "LETTER FACE: OPEN FACE ALUMINUM"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION: 12 V MARQUEE BULBS"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: MARQUEE CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "LETTER FACE: OPEN FACE ALUMINUM"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION: 12 V MARQUEE BULBS"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP,  SERVICEABLE RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE RACEWAY, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: MARQUEE CHANNEL LETTERS WITH ALUMINUM BACKBOARD"}, {"t": "text", "v": "LETTER FACE: OPEN FACE ALUMINUM"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION: 12 V MARQUEE BULBS"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP,  SERVICEABLE RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE RACEWAY, WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: MARQUEE CHANNEL LETTERS WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "LETTER FACE: OPEN FACE ALUMINUM"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION: 12 V MARQUEE BULBS"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2.5 MM FLAT ALUMINUM"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: MARQUEE CHANNEL LETTERS WITH FLAT ACM BACKER"}, {"t": "text", "v": "LETTER FACE: OPEN FACE ALUMINUM"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION: 12 V MARQUEE BULBS"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 4 MM FLAT ACM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: MARQUEE CHANNEL LETTERS WITH FLAT ACRYLIC BACKER"}, {"t": "text", "v": "LETTER FACE: OPEN FACE ALUMINUM"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION: 12 V MARQUEE BULBS"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 8 MM FLAT ACRYLIC BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "OPEN FACE FAUX NEON CHANNEL LETTER",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON"}, {"t": "text", "v": "FACE: ALUMINUM WITH ACRYLIC & NEON TUBING ON FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : FAUX LED NEON TUBING"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON WITH RACEWAY"}, {"t": "text", "v": "FACE: ALUMINUM WITH ACRYLIC & NEON TUBING ON FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\"\" X [WIDTH]\"\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : FAUX LED NEON TUBING"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP,  SERVICEABLE RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "RACEWAY COLOR", "v": "  • RACEWAY COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF RACEWAY WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON WITH ALUMINUM BACKBOARD"}, {"t": "text", "v": "FACE: ALUMINUM WITH ACRYLIC & NEON TUBING ON FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : FAUX LED NEON TUBING"}, {"t": "text", "v": "MOUNTING: BACKBOARD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP, SERVICEABLE BACKBOARD"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF BACKBOARD WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "FACE: ALUMINUM WITH ACRYLIC & NEON TUBING ON FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : FAUX LED NEON TUBING"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2.5 MM FLAT ALUMIUN BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON WITH FLAT ACM BACKER"}, {"t": "text", "v": "FACE: ALUMINUM WITH ACRYLIC & NEON TUBING ON FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : FAUX LED NEON TUBING"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 4 MM FLAT ACM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON WITH FLAT ACRYLIC BACKER"}, {"t": "text", "v": "FACE: ALUMINUM WITH ACRYLIC & NEON TUBING ON FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : FAUX LED NEON TUBING"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 8 MM FLAT ACRYLIC BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "field", "label": "BACKER COLOR", "v": "  • BACKER COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "Face & Side Lit Channel Letters",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE & SIDE LIT CHANNEL LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE & SIDE LIT CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "FACE: ACRYLIC WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP,  SERVICEABLE RACEWAY"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE RACEWAY WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE & SIDE LIT CHANNEL LETTERS WITH BACKBOARD CABINET"}, {"t": "text", "v": "FACE: ACRYLIC WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP SERVICEABLE BACKBOARD"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE BACKBOARD WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE & SIDE LIT CHANNEL LETTERS WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "FACE: ACRYLIC WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2.5MM THICK ALUMINUM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE & SIDE LIT CHANNEL LETTERS WITH FLAT ACM BACKER"}, {"t": "text", "v": "FACE: ACRYLIC WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 4 MM THICK ACM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FACE & SIDE LIT CHANNEL LETTERS WITH FLAT ACRYLIC BACKER"}, {"t": "text", "v": "FACE: ACRYLIC WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 8 MM THICK ACRYLIC BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "Side Lit Channel Letters",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SIDE LIT CHANNEL LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC WITH OPAQUE VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SIDE LIT CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "FACE: ACRYLIC WITH OPAQUE VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP,  SERVICEABLE RACEWAY"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE RACEWAY WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SIDE LIT CHANNEL LETTERS WITH BACKBOARD CABINET"}, {"t": "text", "v": "FACE: ACRYLIC WITH OPAQUE VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP SERVICEABLE BACKBOARD"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE BACKBOARD WITH ON/OFF SWITCH INSTALLED"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SIDE LIT CHANNEL LETTERS WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "FACE: ACRYLIC WITH OPAQUE VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2.5MM THICK ALUMINUM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SIDE LIT CHANNEL LETTERS WITH FLAT ACM BACKER"}, {"t": "text", "v": "FACE: ACRYLIC WITH OPAQUE VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 4 MM THICK ACM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SIDE LIT CHANNEL LETTERS WITH FLAT ACRYLIC BACKER"}, {"t": "text", "v": "FACE: ACRYLIC WITH OPAQUE VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "SIDES: TRANSLUCENT ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 8 MM THICK ACRYLIC BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CHANNEL LETTERS", signtype: "Vacuum Formed Channel Letters",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "A", sideview: "", lines: [] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "\"SIGN TYPE: VACUUM FORMED CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "FACE: VACUUM FORMED ACRYLIC"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\"\" X [WIDTH]\"\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP, SERVICEABLE ALUMINUM RACEWAY"}, {"t": "application", "v": "APPLICATION: [APPLICATION]\""}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: VACUUM FORMED CHANNEL LETTERS WITH ALUMINUM BACKBOARD"}, {"t": "text", "v": "FACE: VACUUM FORMED ACRYLIC"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP, SERVICEABLE ALUMINUM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: VACUUM FORMED CHANNEL LETTERS WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "FACE: VACUUM FORMED ACRYLIC"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2.5 MM THICK ALUMINUM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: VACUUM FORMED CHANNEL LETTERS WITH FLAT ACM BACKER"}, {"t": "text", "v": "FACE: VACUUM FORMED ACRYLIC"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 4 MM THICK ACM BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: VACUUM FORMED CHANNEL LETTERS WITH FLAT ACRYLIC BACKER"}, {"t": "text", "v": "FACE: VACUUM FORMED ACRYLIC"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500 K LED MODULES (3 YEARS WARRANTY)"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 8 MM THICK ACRYLIC BACKER"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "NON ILLUMINATED FABRICATED CHANNEL LETTERS", signtype: "Fabricated Channel Letters",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : NON ILLUMINATED FABRICATED CHANNEL LETTERS"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH/STUD MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Raceway Mount (2\")", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : NON ILLUMINATED FABRICATED CHANNEL LETTERS WITH RACEWAY"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: RACEWAY MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP, 6\" TALL ALUMINUM RACEWAY"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Backboard Cabinet (2\")", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : NON ILLUMINATED FABRICATED CHANNEL LETTERS WITH ALUMINUM BACKBOARD"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2\" DEEP ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Aluminum Backer (2.5 mm)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : NON ILLUMINATED FABRICATED CHANNEL LETTERS WITH FLAT ALUMINUM BACKER"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 2.5 MM THICK ALUMINUM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat ACM Backer (4mm)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : NON ILLUMINATED FABRICATED CHANNEL LETTERS WITH FLAT ACM BACKER"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 4 MM THICK ACM BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Flat Acrylic Backer (8mm)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE : NON ILLUMINATED FABRICATED CHANNEL LETTERS WITH FLAT ACRYLIC BACKER"}, {"t": "text", "v": "LETTER FACE: SS/ALUMINUM FACE"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: BACKER MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: 8 MM THICK ACRYLIC BACKER"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "DIMENSIONAL FLAT CUT LETTERS", signtype: "Flat Cut Acrylic/PVC Letters",
    hasThickness: true,
    leaves: [
      { thickness: "1/4\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/4\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/4\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/4\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/4\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/4\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/2\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/2\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1/2\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/2\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/2\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1/2\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/2\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/2\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1/2\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "3/4\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 3/4\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 3/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "3/4\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 3/4\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 3/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "3/4\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 3/4\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 3/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1\" FLAT CUT ACRYLIC LETTERS"}, {"t": "text", "v": "FACE: ACRYLIC"}, {"t": "text", "v": "LETTERS THICKNESS: 1\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "DIMENSIONAL FLAT CUT LETTERS", signtype: "Flat Cut Aluminum Letters",
    hasThickness: true,
    leaves: [
      { thickness: "1/8\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/8\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/8\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/8\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/8\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/8\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/8\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/8\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/8\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/4\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/4\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/4\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/4\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/4\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/4\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/4\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "3/8\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 3/8\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 3/8\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "3/8\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 3/8\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 3/8\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "3/8\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 3/8\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 3/8\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/2\"", mounting: "Flush Mount (VHB)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/2\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/2\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH VHB)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/2\"", mounting: "Flush Mount (Screws)", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/2\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/2\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT (WITH SCREWS)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "1/2\"", mounting: "Stud Mount", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: 1/2\" FLAT CUT ALUMINUM LETTERS"}, {"t": "text", "v": "FACE: ALUMINUM/SS FACE"}, {"t": "text", "v": "LETTERS THICKNESS: 1/2\""}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "ILLUMINATION : N/A"}, {"t": "text", "v": "MOUNTING: STUD MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Single Sided Face Lit Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "N/A", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SINGLE SIDED FACE LIT CABINET"}, {"t": "text", "v": "FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: STANDARD/METALLIC TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "text", "v": "APPLICATION: EXTERIOR"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Single Sided Face & Halo Lit Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SINGLE SIDED FACE & HALO LIT CABINET"}, {"t": "text", "v": "FACE: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "BACK: FROSTED ACRYLIC"}, {"t": "text", "v": "TRIM CAP: STANDARD/METALLIC TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "text", "v": "APPLICATION: EXTERIOR"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Double Sided Illuminated Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: DOUBLE SIDED ILLUMINATED CABINET"}, {"t": "text", "v": "FACES: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: STANDARD/METALLIC TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Single Sided Push Thru Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SINGLE SIDED FACE LIT PUSH THRU CABINET"}, {"t": "text", "v": "FACE: ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Single Sided Face & Halo lit Push Thru Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SINGLE SIDED FACE AND HALO LIT PUSH THRU CABINET"}, {"t": "text", "v": "FACE: ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "BACK: FROSTED ACRYLIC"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Double Sided Push Thru Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: DOUBLE SIDED FACE LIT PUSH THRU CABINET"}, {"t": "text", "v": "FACES: ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Single Sided Routed & Backed up Acrylic Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SINGLE SIDED ROUTED & BACKED UP ACRYLIC CABINET"}, {"t": "text", "v": "FACE: ROUTED ALUMINUM FACE WITH BACKED UP ACRYLIC LETTERS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "ILLUMINATED CABINETS", signtype: "Double Sided Routed & Backed up Acrylic Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: DOUBLE SIDED ROUTED AND BACKED UP ACRYLIC CABINET"}, {"t": "text", "v": "FACES: ROUTED ALUMINUM FACE WITH ROUTED AND BACKED UP ACRYLIC LETTERS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "RACEWAY/BACKER: N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "NON ILLUMINATED CABINETS", signtype: "Single Sided Non Illuminated Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "N/A", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: SINGLE SIDED NON-ILLUMINATED CABINET"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "FACES: ALUMINUM/SS"}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : N/A"}, {"t": "text", "v": "MOUNTING: FLUSH MOUNT"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "NON ILLUMINATED CABINETS", signtype: "Double Sided Non Illuminated Cabinet",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: DOUBLE SIDED NON-ILLUMINATED CABINET"}, {"t": "text", "v": "FACES: ALUMINUM/SS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURNS COLOR", "v": "  • FACE & RETURNS COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "BLADE SIGNS", signtype: "Fabricated Illumimated Blade Sign",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "N/A", package: "A", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: DOUBLE SIDED ILLUMINATED BLADE SIGN"}, {"t": "text", "v": "FACES: ACRYLIC FACE WITH VINYL APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "TRIM CAP: STANDARD/METALLIC TRIM CAP"}, {"t": "text", "v": "ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "field", "label": "RETURN & TRIM COLOR", "v": "  • RETURN & TRIM COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}, {"t": "text", "v": ""}, {"t": "text", "v": "* POWER SUPPLY TO BE INSIDE OF CABINET WITH ON/OFF SWITCH INSTALLED"}] },
    ],
  },
  {
    family: "BLADE SIGNS", signtype: "Fabricated Non Illuminated Blade Sign",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: DOUBLE SIDED NON-ILLUMINATED BLADE SIGN"}, {"t": "text", "v": "FACES: ALUMINUM FACE WITH VINYL/PAINT APPLICATION"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "depth", "v": "RETURNS: [DEPTH]\""}, {"t": "text", "v": "ILLUMINATED : N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE & RETURN COLOR", "v": "  • FACE & RETURN COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "BLADE SIGNS", signtype: "Flat Blade Sign",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "", package: "B", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FLAT BLADE SIGN"}, {"t": "text", "v": "BLADE FACE: ALUMINUM/SS"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "text", "v": "BLADE THICKNESS: 2.5 MM"}, {"t": "text", "v": "ILLUMINATED : N/A"}, {"t": "text", "v": "COLOR SPECS:"}, {"t": "field", "label": "FACE COLOR", "v": "  • FACE COLOR: [ASK REP]"}, {"t": "text", "v": "FINISH: SATIN"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "LED NEON SIGNS", signtype: "Faux LED Neon Sign",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "C", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FAUX LED NEON SIGN"}, {"t": "text", "v": "FACE: ACRYLIC WITH FAUX LED NEON"}, {"t": "field", "label": "NEON COLORS", "v": "NEON COLORS: [ASK REP]"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "field", "label": "SHAPE", "v": "SHAPE: [ASK REP]"}, {"t": "text", "v": "ILLUMINATED : FAUX NEON LED"}, {"t": "text", "v": "MOUNTING: WALL MOUNTED"}, {"t": "field", "label": "ACRYLIC", "v": "ACRYLIC: [ASK REP]"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Ceiling Hung", package: "D", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: FAUX LED NEON SIGN"}, {"t": "text", "v": "FACE: ACRYLIC WITH FAUX LED NEON"}, {"t": "field", "label": "NEON COLORS", "v": "NEON COLORS: [ASK REP]"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "field", "label": "SHAPE", "v": "SHAPE: [ASK REP]"}, {"t": "text", "v": "ILLUMINATED : FAUX NEON LED"}, {"t": "text", "v": "MOUNTING: CEILING MOUNTED"}, {"t": "field", "label": "ACRYLIC", "v": "ACRYLIC: [ASK REP]"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
  {
    family: "LED NEON SIGNS", signtype: "Faux Acrylic Neon Sign",
    hasThickness: false,
    leaves: [
      { thickness: "", mounting: "Flush Mount", package: "C", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: ACRYLIC FAUX LED NEON SIGN"}, {"t": "text", "v": "FACE: ACRYLIC WITH FAUX LED NEON"}, {"t": "field", "label": "NEON COLORS", "v": "NEON COLORS: [ASK REP]"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "field", "label": "SHAPE", "v": "SHAPE: [ASK REP]"}, {"t": "text", "v": "ILLUMINATED : FAUX NEON LED"}, {"t": "text", "v": "MOUNTING: WALL MOUNTED"}, {"t": "field", "label": "ACRYLIC", "v": "ACRYLIC: [ASK REP]"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
      { thickness: "", mounting: "Ceiling Hung", package: "", sideview: "", lines: [{"t": "text", "v": "SIGN TYPE: ACRYLIC FAUX LED NEON SIGN"}, {"t": "text", "v": "FACE: ACRYLIC WITH FAUX LED NEON"}, {"t": "field", "label": "NEON COLORS", "v": "NEON COLORS: [ASK REP]"}, {"t": "dims", "v": "OVERALL DIMENSIONS: [HEIGHT]\" X [WIDTH]\""}, {"t": "field", "label": "SHAPE", "v": "SHAPE: [ASK REP]"}, {"t": "text", "v": "ILLUMINATED : FAUX NEON LED"}, {"t": "text", "v": "MOUNTING: CEILING MOUNTED"}, {"t": "field", "label": "ACRYLIC", "v": "ACRYLIC: [ASK REP]"}, {"t": "application", "v": "APPLICATION: [APPLICATION]"}] },
    ],
  },
]